[package]
name = "paq1_storage_core"
version = "0.2.0"
edition = "2024"

[dependencies]
paq1-lib-error-handler = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
serde = { version = "1.0.218", features = ["derive"] }